
services:
  flask:
    build: .
    command: flask run
    volumes:
      - .:/code
    ports: 
      - 5000:5000
    env_file: 
      - ./.flask.env
    profiles: ["basic","admin"]

  mongo:
    image: mongo:4.2.16
    restart: always
    volumes: 
     - ./mongo_database:/data/db 
     - ./backup:/backup
    env_file: 
      - ./.mongo.env
    profiles: ["basic","admin"]

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - 8081:8081
    env_file: 
      - ./.mongo-express.env
    depends_on: 
      - mongo
    profiles: ["admin"]
